-- Expand catalog: drinks, juices, energy, full cigarettes, heated/vape.
insert into products (id, name, description, price, cat, photo, sort_order, stock) values
  ('esp', 'Espresso', 'Μονός, κοντός, με κρέμα', 1.8, 'coffee', '/images/espresso.jpg', 0, 40),
  ('espd', 'Espresso διπλός', 'Όταν η μέρα το απαιτεί', 2.3, 'coffee', '/images/products/espresso-double.jpg', 1, 40),
  ('cap', 'Cappuccino', 'Γάλα, μικροαφρός', 2.5, 'coffee', '/images/products/cappuccino.jpg', 2, 40),
  ('fe', 'Freddo espresso', 'Κρύος, σφιχτός', 2.4, 'coffee', '/images/freddo.jpg', 3, 40),
  ('fc', 'Freddo cappuccino', 'Με αφρόγαλα', 2.8, 'coffee', '/images/products/freddo-cap.jpg', 4, 40),
  ('frap', 'Frappe', 'Κρύος, χτυπημένος', 2.3, 'coffee', '/images/products/frappe.jpg', 5, 40),
  ('el', 'Ελληνικός', 'Μεζές της υπομονής', 1.8, 'coffee', '/images/products/ellinikos.jpg', 6, 40),
  ('fil', 'Φίλτρου', 'Καθαρός, αργός', 2.2, 'coffee', '/images/products/filter.jpg', 7, 40),
  ('lat', 'Latte', 'Πιο γάλα, πιο μαλακός', 3.0, 'coffee', '/images/products/latte.jpg', 8, 40),
  ('koul', 'Κουλούρι Θεσσαλονίκης', 'Σουσάμι, ζεστό αν προλάβεις', 0.8, 'bread', '/images/bread.jpg', 9, 18),
  ('loaf', 'Σταρένιο καρβέλι', 'Της ημέρας', 2.5, 'bread', '/images/products/loaf.jpg', 10, 18),
  ('seed', 'Πολύσπορο', 'Για το βράδυ στο σπίτι', 2.8, 'bread', '/images/products/seeded.jpg', 11, 18),
  ('cro', 'Croissant', 'Απλό, σωστό', 1.8, 'bread', '/images/products/croissant.jpg', 12, 18),
  ('tyr', 'Τυρόπιτα', 'Φύλλο, φέτα', 2.2, 'bread', '/images/products/tyropita.jpg', 13, 18),
  ('spa', 'Σπανακόπιτα', 'Χόρτα, άνηθος', 2.2, 'bread', '/images/products/spanakopita.jpg', 14, 18),
  ('cola', 'Coca-Cola', '330ml, κλασική', 1.5, 'drinks', '/images/products/cola-can.jpg', 15, 36),
  ('colaz', 'Coca-Cola Zero', '330ml, χωρίς ζάχαρη', 1.5, 'drinks', '/images/products/cola-zero.jpg', 16, 36),
  ('fanta', 'Fanta Πορτοκάλι', '330ml', 1.5, 'drinks', '/images/products/fanta-orange.jpg', 17, 36),
  ('fantal', 'Fanta Λεμόνι', '330ml', 1.5, 'drinks', '/images/products/fanta-lemon.jpg', 18, 36),
  ('sprite', 'Sprite', '330ml', 1.5, 'drinks', '/images/products/sprite-can.jpg', 19, 36),
  ('xixo-p', 'XIXO Ice Tea Ροδάκινο', '250ml', 1.2, 'drinks', '/images/products/xixo-peach.jpg', 20, 36),
  ('xixo-l', 'XIXO Ice Tea Λεμόνι', '250ml', 1.2, 'drinks', '/images/products/xixo-lemon.jpg', 21, 36),
  ('xixo-s', 'XIXO Ice Tea Φράουλα', '250ml', 1.2, 'drinks', '/images/products/xixo-berry.jpg', 22, 36),
  ('xixo-t', 'XIXO Tutti Frutti', '250ml', 1.2, 'drinks', '/images/products/xixo-tutti.jpg', 23, 36),
  ('amita-o', 'Amita Πορτοκάλι', '330ml, φυσικός χυμός', 1.9, 'juice', '/images/products/juice-orange.jpg', 24, 36),
  ('amita-a', 'Amita Μήλο', '250ml', 1.8, 'juice', '/images/products/juice-apple.jpg', 25, 36),
  ('amita-p', 'Amita Ροδάκινο', '250ml', 1.4, 'juice', '/images/products/juice-peach.jpg', 26, 36),
  ('amita-v', 'Amita Βύσσινο', '250ml', 1.4, 'juice', '/images/products/juice-cherry.jpg', 27, 36),
  ('amita-m', 'Amita Motion', '330ml, πορτοκάλι-καρότο-λεμόνι', 1.9, 'juice', '/images/products/juice-orange.jpg', 28, 36),
  ('amita-mix', 'Amita Πορτοκάλι Μήλο Βερίκοκο', '250ml', 1.4, 'juice', '/images/products/juice-peach.jpg', 29, 36),
  ('rb', 'Red Bull', '250ml', 2.2, 'energy', '/images/products/redbull.jpg', 30, 36),
  ('rbsf', 'Red Bull Sugarfree', '250ml, χωρίς ζάχαρη', 2.2, 'energy', '/images/products/redbull.jpg', 31, 36),
  ('hell', 'Hell Classic', '250ml', 1.5, 'energy', '/images/products/hell.jpg', 32, 36),
  ('hellz', 'Hell Zero', '250ml, χωρίς ζάχαρη', 1.5, 'energy', '/images/products/hell.jpg', 33, 36),
  ('wat', 'Νερό', '500ml, κρύο', 0.5, 'market', '/images/products/water.jpg', 34, 36),
  ('choco', 'Σοκολάτα', 'Μπάρα', 1.8, 'market', '/images/products/chocolate.jpg', 35, 36),
  ('chips', 'Πατατάκια', 'Κλασική σακούλα', 1.5, 'market', '/images/products/chips.jpg', 36, 36),
  ('gum', 'Τσίχλες', 'Για μετά τον καφέ', 0.8, 'market', '/images/products/gum.jpg', 37, 36),
  ('marl', 'Marlboro Red', 'Κόκκινο πακέτο', 5.5, 'smokes', '/images/products/marlboro.jpg', 38, 24),
  ('marlg', 'Marlboro Gold', 'Χρυσό πακέτο', 5.5, 'smokes', '/images/products/pack-gold.jpg', 39, 24),
  ('marlt', 'Marlboro Touch', 'Slim', 5.5, 'smokes', '/images/products/pack-slim.jpg', 40, 24),
  ('winst', 'Winston Classic', 'Κλασικό', 5.2, 'smokes', '/images/products/winston.jpg', 41, 24),
  ('winstb', 'Winston Blue', 'Μπλε', 5.2, 'smokes', '/images/products/pack-blue.jpg', 42, 24),
  ('davi', 'Davidoff Slim', 'Slim', 5.8, 'smokes', '/images/products/davidoff.jpg', 43, 24),
  ('davic', 'Davidoff Classic', 'Κλασικό', 5.8, 'smokes', '/images/products/davidoff.jpg', 44, 24),
  ('camely', 'Camel Yellow', 'Κίτρινο', 5.2, 'smokes', '/images/products/pack-gold.jpg', 45, 24),
  ('camelb', 'Camel Blue', 'Μπλε', 5.2, 'smokes', '/images/products/pack-blue.jpg', 46, 24),
  ('lucky', 'Lucky Strike', 'Κόκκινο', 5.0, 'smokes', '/images/products/pack-red.jpg', 47, 24),
  ('parl', 'Parliament', 'Aqua slim', 5.8, 'smokes', '/images/products/pack-slim.jpg', 48, 24),
  ('kar', 'Karelia Red', 'Κόκκινο', 4.8, 'smokes', '/images/products/pack-red.jpg', 49, 24),
  ('kars', 'Karelia Slim', 'Slim', 5.0, 'smokes', '/images/products/pack-slim.jpg', 50, 24),
  ('pall', 'Pall Mall', 'Κόκκινο', 4.7, 'smokes', '/images/products/pack-gold.jpg', 51, 24),
  ('lm', 'L&M Blue', 'Μπλε', 4.8, 'smokes', '/images/products/pack-blue.jpg', 52, 24),
  ('assos', 'Assos', 'Διεθνές', 4.5, 'smokes', '/images/products/pack-red.jpg', 53, 24),
  ('chest', 'Chesterfield', 'Κόκκινο', 4.7, 'smokes', '/images/products/pack-red.jpg', 54, 24),
  ('ter-br', 'Terea Bronze', 'IQOS ILUMA · ζεστό χαρμάνι', 4.0, 'heat', '/images/products/terea-warm.jpg', 55, 24),
  ('ter-si', 'Terea Sienna', 'IQOS ILUMA · νότες ξύλου', 4.0, 'heat', '/images/products/terea-warm.jpg', 56, 24),
  ('ter-am', 'Terea Amber', 'IQOS ILUMA · ισορροπημένο', 4.0, 'heat', '/images/products/terea-warm.jpg', 57, 24),
  ('ter-ru', 'Terea Russet', 'IQOS ILUMA · έντονο', 4.0, 'heat', '/images/products/terea-warm.jpg', 58, 24),
  ('ter-tk', 'Terea Teak', 'IQOS ILUMA · πλούσιο', 4.0, 'heat', '/images/products/terea-warm.jpg', 59, 24),
  ('ter-tu', 'Terea Turquoise', 'IQOS ILUMA · ζωηρό', 4.0, 'heat', '/images/products/terea-cool.jpg', 60, 24),
  ('ter-ye', 'Terea Yellow', 'IQOS ILUMA · αρωματικό', 4.0, 'heat', '/images/products/terea-cool.jpg', 61, 24),
  ('ter-sv', 'Terea Silver', 'IQOS ILUMA · απαλό', 4.0, 'heat', '/images/products/terea-cool.jpg', 62, 24),
  ('evo-bu', 'Ploom EVO Burgundy', 'Ράβδοι καπνού Ploom', 4.25, 'heat', '/images/products/evo-pack.jpg', 63, 24),
  ('evo-tn', 'Ploom EVO Tan', 'Πλούσιο, γλυκό', 4.25, 'heat', '/images/products/evo-pack.jpg', 64, 24),
  ('evo-ga', 'Ploom EVO Garnet', 'Αρωματικό', 4.25, 'heat', '/images/products/evo-pack.jpg', 65, 24),
  ('evo-go', 'Ploom EVO Gold', 'Ήπιο χαρμάνι', 4.25, 'heat', '/images/products/pack-gold.jpg', 66, 24),
  ('evo-sv', 'Ploom EVO Silver', 'Απαλή γεύση καπνού', 4.25, 'heat', '/images/products/pack-slim.jpg', 67, 24),
  ('evo-gr', 'Ploom EVO Green', 'Φρεσκάδα', 4.25, 'heat', '/images/products/neo-mint.jpg', 68, 24),
  ('evo-te', 'Ploom EVO Teal', 'Δροσερές νότες', 4.25, 'heat', '/images/products/terea-cool.jpg', 69, 24),
  ('neo-cl', 'glo neo Classic Tobacco', '20 ράβδοι · glo Hyper', 3.0, 'heat', '/images/products/neo-pack.jpg', 70, 24),
  ('neo-go', 'glo neo Golden Tobacco', 'Κλασικό χρυσό', 3.0, 'heat', '/images/products/neo-pack.jpg', 71, 24),
  ('neo-te', 'glo neo Terracotta', 'Πλούσιος καπνός', 3.0, 'heat', '/images/products/neo-pack.jpg', 72, 24),
  ('neo-az', 'glo neo Azure', 'Δροσερές νότες', 3.0, 'heat', '/images/products/terea-cool.jpg', 73, 24),
  ('neo-sc', 'glo neo Scarlet', 'Ισορροπημένο', 3.0, 'heat', '/images/products/evo-pack.jpg', 74, 24),
  ('neo-gr', 'glo neo Green', 'Μέντα', 3.0, 'heat', '/images/products/neo-mint.jpg', 75, 24),
  ('neo-ar', 'glo neo Arctic', 'Έντονη δροσιά', 3.0, 'heat', '/images/products/neo-mint.jpg', 76, 24),
  ('v1-tob', 'VEEV ONE Classic Tobacco', 'Pod · καπνός', 3.2, 'heat', '/images/products/veev-tobacco.jpg', 77, 24),
  ('v1-bal', 'VEEV ONE Balanced Tobacco', 'Pod · καφές & καπνός', 3.2, 'heat', '/images/products/veev-tobacco.jpg', 78, 24),
  ('v1-mint', 'VEEV ONE Blue Mint', 'Pod · μέντα', 3.2, 'heat', '/images/products/veev-mint.jpg', 79, 24),
  ('v1-sea', 'VEEV ONE Sea Mint', 'Pod · θαλασσινή μέντα', 3.2, 'heat', '/images/products/veev-mint.jpg', 80, 24),
  ('v1-str', 'VEEV ONE Strawberry', 'Pod · φράουλα', 3.2, 'heat', '/images/products/veev-fruit.jpg', 81, 24),
  ('v1-man', 'VEEV ONE Mango', 'Pod · μάνγκο', 3.2, 'heat', '/images/products/veev-fruit.jpg', 82, 24),
  ('v1-blu', 'VEEV ONE Blueberry', 'Pod · blueberry', 3.2, 'heat', '/images/products/veev-fruit.jpg', 83, 24),
  ('v1-wat', 'VEEV ONE Watermelon', 'Pod · καρπούζι', 3.2, 'heat', '/images/products/veev-fruit.jpg', 84, 24),
  ('v1-gra', 'VEEV ONE Grape', 'Pod · σταφύλι', 3.2, 'heat', '/images/products/veev-fruit.jpg', 85, 24),
  ('v1-app', 'VEEV ONE Sour Apple', 'Pod · πράσινο μήλο', 3.2, 'heat', '/images/products/veev-fruit.jpg', 86, 24),
  ('v1-che', 'VEEV ONE Cherry', 'Pod · κεράσι', 3.2, 'heat', '/images/products/veev-fruit.jpg', 87, 24),
  ('v1-mel', 'VEEV ONE Melon Coconut', 'Pod · πεπόνι καρύδα', 3.2, 'heat', '/images/products/veev-fruit.jpg', 88, 24),
  ('vp-gold', 'VEEV Prime Gold Tobacco', 'Pod inPRIME · καπνός', 4.0, 'heat', '/images/products/veev-tobacco.jpg', 89, 24),
  ('vp-mint', 'VEEV Prime Blue Mint', 'Pod inPRIME · μέντα', 4.0, 'heat', '/images/products/veev-mint.jpg', 90, 24),
  ('vp-str', 'VEEV Prime Strawberry', 'Pod inPRIME · φράουλα', 4.0, 'heat', '/images/products/veev-fruit.jpg', 91, 24),
  ('vp-app', 'VEEV Prime Sour Apple', 'Pod inPRIME · μήλο', 4.0, 'heat', '/images/products/veev-fruit.jpg', 92, 24),
  ('vp-ll', 'VEEV Prime Lemon Lime', 'Pod inPRIME · εσπεριδοειδή', 4.0, 'heat', '/images/products/veev-mint.jpg', 93, 24),
  ('vp-brs', 'VEEV Prime Blue Raspberry', 'Pod inPRIME · raspberry', 4.0, 'heat', '/images/products/veev-fruit.jpg', 94, 24),
  ('vp-che', 'VEEV Prime Cherry', 'Pod inPRIME · κεράσι', 4.0, 'heat', '/images/products/veev-fruit.jpg', 95, 24)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  cat = excluded.cat,
  photo = excluded.photo,
  sort_order = excluded.sort_order;
