-- Official drink photos + full fridge catalog.
insert into products (id, name, description, price, cat, photo, sort_order, stock) values
  ('esp', 'Espresso', 'Μονός, κοντός, με κρέμα', 1.8, 'coffee', '/images/espresso.jpg', 0, 40),
  ('espd', 'Espresso διπλός', 'Όταν η μέρα το απαιτεί', 2.3, 'coffee', '/images/products/espresso-double.jpg', 1, 40),
  ('cap', 'Cappuccino', 'Γάλα, μικροαφρός', 2.5, 'coffee', '/images/products/cappuccino.jpg', 2, 40),
  ('fe', 'Freddo espresso', 'Κρύος, σφιχτός', 2.4, 'coffee', '/images/freddo.jpg', 3, 40),
  ('fc', 'Freddo cappuccino', 'Με αφρόγαλα', 2.8, 'coffee', '/images/products/freddo-cap.jpg', 4, 40),
  ('frap', 'Frappe', 'Κρύος, χτυπημένος', 2.3, 'coffee', '/images/products/frappe.jpg', 5, 40),
  ('el', 'Ελληνικός', 'Μεζές της υπομονής', 1.8, 'coffee', '/images/products/ellinikos.jpg', 6, 40),
  ('fil', 'Φίλτρου', 'Καθαρός, αργός', 2.2, 'coffee', '/images/products/filter.jpg', 7, 40),
  ('lat', 'Latte', 'Πιο γάλα, πιο μαλακός', 3.0, 'coffee', '/images/products/latte.jpg', 8, 40),
  ('koul', 'Κουλούρι Θεσσαλονίκης', 'Σουσάμι, ζεστό αν προλάβεις', 0.8, 'bread', '/images/bread.jpg', 9, 18),
  ('loaf', 'Σταρένιο καρβέλι', 'Της ημέρας', 2.5, 'bread', '/images/products/loaf.jpg', 10, 18),
  ('seed', 'Πολύσπορο', 'Για το βράδυ στο σπίτι', 2.8, 'bread', '/images/products/seeded.jpg', 11, 18),
  ('cro', 'Croissant', 'Απλό, σωστό', 1.8, 'bread', '/images/products/croissant.jpg', 12, 18),
  ('tyr', 'Τυρόπιτα', 'Φύλλο, φέτα', 2.2, 'bread', '/images/products/tyropita.jpg', 13, 18),
  ('spa', 'Σπανακόπιτα', 'Χόρτα, άνηθος', 2.2, 'bread', '/images/products/spanakopita.jpg', 14, 18),
  ('cola', 'Coca-Cola', '330ml κουτάκι', 1.5, 'drinks', '/images/products/coca-cola.jpg', 15, 36),
  ('colaz', 'Coca-Cola Zero', '330ml κουτάκι', 1.5, 'drinks', '/images/products/coca-cola-zero.jpg', 16, 36),
  ('cola-lem', 'Coca-Cola Lemon', '330ml κουτάκι', 1.5, 'drinks', '/images/products/coca-cola-lemon.jpg', 17, 36),
  ('cola-lt', 'Coca-Cola Light', '330ml κουτάκι', 1.5, 'drinks', '/images/products/coca-cola-light.jpg', 18, 36),
  ('cola-zcaf', 'Coca-Cola Zero Caffeine', '330ml κουτάκι', 1.5, 'drinks', '/images/products/coca-cola-zero-caffeine.jpg', 19, 36),
  ('fanta', 'Fanta Πορτοκάλι', '330ml κουτάκι', 1.5, 'drinks', '/images/products/fanta-portokali.jpg', 20, 36),
  ('fantal', 'Fanta Λεμονάδα', '330ml κουτάκι', 1.5, 'drinks', '/images/products/fanta-lemonada.jpg', 21, 36),
  ('fanta-ex', 'Fanta Exotic', '330ml κουτάκι', 1.5, 'drinks', '/images/products/fanta-exotic.jpg', 22, 36),
  ('fanta-bl', 'Fanta Μπλε', '330ml κουτάκι', 1.5, 'drinks', '/images/products/fanta-blue.jpg', 23, 36),
  ('fanta-z', 'Fanta Zero', '330ml κουτάκι', 1.5, 'drinks', '/images/products/fanta-zero.jpg', 24, 36),
  ('sprite', 'Sprite', '330ml κουτάκι', 1.5, 'drinks', '/images/products/sprite.jpg', 25, 36),
  ('spritez', 'Sprite Zero', '330ml κουτάκι', 1.5, 'drinks', '/images/products/sprite-zero.jpg', 26, 36),
  ('sch-ton', 'Schweppes Indian Tonic', '330ml κουτάκι', 1.7, 'drinks', '/images/products/schweppes-tonic.jpg', 27, 36),
  ('sch-gf', 'Schweppes Pink Grapefruit', '330ml κουτάκι', 1.7, 'drinks', '/images/products/schweppes-grapefruit.jpg', 28, 36),
  ('sch-soda', 'Schweppes Soda Water', '330ml κουτάκι', 1.5, 'drinks', '/images/products/schweppes-soda.jpg', 29, 36),
  ('sch-trop', 'Schweppes Tropical Fusion', '330ml κουτάκι', 1.7, 'drinks', '/images/products/schweppes-tropical.jpg', 30, 36),
  ('sch-or', 'Schweppes Orangeade', '330ml κουτάκι', 1.7, 'drinks', '/images/products/schweppes-orangeade.jpg', 31, 36),
  ('sch-lem', 'Schweppes Soda Lemon', '330ml κουτάκι', 1.7, 'drinks', '/images/products/schweppes-soda-lemon.jpg', 32, 36),
  ('sch-gin', 'Schweppes Ginger Ale', '330ml κουτάκι', 1.7, 'drinks', '/images/products/schweppes-ginger.jpg', 33, 36),
  ('sch-bit', 'Schweppes Bitter Lemon', '330ml κουτάκι', 1.7, 'drinks', '/images/products/schweppes-bitter-lemon.jpg', 34, 36),
  ('sch-moj', 'Schweppes Mojito', '330ml κουτάκι, χωρίς αλκοόλ', 1.7, 'drinks', '/images/products/schweppes-mojito.jpg', 35, 36),
  ('sch-pom', 'Schweppes Pomegranate', '330ml κουτάκι', 1.7, 'drinks', '/images/products/schweppes-pomegranate.jpg', 36, 36),
  ('sch-ber', 'Schweppes Bergamot Hibiscus', '330ml κουτάκι', 1.7, 'drinks', '/images/products/schweppes-bergamot.jpg', 37, 36),
  ('sch-ch', 'Schweppes Sour Cherry', '330ml κουτάκι', 1.7, 'drinks', '/images/products/schweppes-cherry.jpg', 38, 36),
  ('blk-lg', 'Black Lemon Lemongrass', '330ml κουτάκι', 1.8, 'drinks', '/images/products/black-lemongrass.jpg', 39, 36),
  ('blk-lgz', 'Black Lemon Lemongrass Zero', '330ml κουτάκι', 1.8, 'drinks', '/images/products/black-lemongrass-zero.jpg', 40, 36),
  ('blk-ph', 'Black Peach Hibiscus', '330ml κουτάκι', 1.8, 'drinks', '/images/products/black-peach-hibiscus.jpg', 41, 36),
  ('blk-pr', 'Black Peach Rose', '330ml κουτάκι', 1.8, 'drinks', '/images/products/black-peach-rose.jpg', 42, 36),
  ('blk-lm', 'Black Lime Mint', '330ml κουτάκι', 1.8, 'drinks', '/images/products/black-lime-mint.jpg', 43, 36),
  ('blk-pas', 'Black Passion Fruit', '330ml κουτάκι', 1.8, 'drinks', '/images/products/black-passion.jpg', 44, 36),
  ('fru-o', 'Frulite Πορτοκάλι', '330ml κουτάκι', 1.4, 'drinks', '/images/products/frulite-portokali.jpg', 45, 36),
  ('fru-s', 'Frulite Φράουλα', '330ml κουτάκι', 1.4, 'drinks', '/images/products/frulite-fraoula.jpg', 46, 36),
  ('fru-v', 'Frulite Βερίκοκο', '330ml κουτάκι', 1.4, 'drinks', '/images/products/frulite-verikoko.jpg', 47, 36),
  ('fru-p', 'Frulite Ροδάκινο', '330ml κουτάκι', 1.4, 'drinks', '/images/products/frulite-rodakino.jpg', 48, 36),
  ('fru-a', 'Frulite Μήλο', '330ml κουτάκι', 1.4, 'drinks', '/images/products/frulite-milo.jpg', 49, 36),
  ('fru-c', 'Frulite Βύσσινο', '330ml κουτάκι', 1.4, 'drinks', '/images/products/frulite-vyssino.jpg', 50, 36),
  ('fru-b', 'Frulite Μπανάνα', '330ml κουτάκι', 1.4, 'drinks', '/images/products/frulite-banana.jpg', 51, 36),
  ('xixo-p', 'XIXO Ice Tea Ροδάκινο', '250ml', 1.2, 'drinks', '/images/products/xixo-peach.jpg', 52, 36),
  ('xixo-l', 'XIXO Ice Tea Λεμόνι', '250ml', 1.2, 'drinks', '/images/products/xixo-lemon.jpg', 53, 36),
  ('xixo-s', 'XIXO Ice Tea Φράουλα', '250ml', 1.2, 'drinks', '/images/products/xixo-berry.jpg', 54, 36),
  ('xixo-t', 'XIXO Tutti Frutti', '250ml', 1.2, 'drinks', '/images/products/xixo-tutti.jpg', 55, 36),
  ('pow-or', 'Powerade Orange', '500ml', 1.8, 'drinks', '/images/products/powerade-orange.jpg', 56, 36),
  ('pow-bl', 'Powerade Blood Orange', '500ml', 1.8, 'drinks', '/images/products/powerade-blood.jpg', 57, 36),
  ('pow-ci', 'Powerade Citrus', '500ml', 1.8, 'drinks', '/images/products/powerade-citrus.jpg', 58, 36),
  ('pow-mb', 'Powerade Mountain Blast', '500ml', 1.8, 'drinks', '/images/products/powerade-blast.jpg', 59, 36),
  ('pow-mbz', 'Powerade Mountain Blast Zero', '500ml', 1.8, 'drinks', '/images/products/powerade-blast-zero.jpg', 60, 36),
  ('amita-o', 'Amita Πορτοκάλι', '330ml, φυσικός χυμός', 1.9, 'juice', '/images/products/juice-orange.jpg', 61, 36),
  ('amita-a', 'Amita Μήλο', '250ml', 1.8, 'juice', '/images/products/juice-apple.jpg', 62, 36),
  ('amita-p', 'Amita Ροδάκινο', '250ml', 1.4, 'juice', '/images/products/juice-peach.jpg', 63, 36),
  ('amita-v', 'Amita Βύσσινο', '250ml', 1.4, 'juice', '/images/products/juice-cherry.jpg', 64, 36),
  ('amita-m', 'Amita Motion', '330ml, πορτοκάλι-καρότο-λεμόνι', 1.9, 'juice', '/images/products/amita-motion.jpg', 65, 36),
  ('amita-mix', 'Amita Πορτοκάλι Μήλο Βερίκοκο', '250ml', 1.4, 'juice', '/images/products/juice-peach.jpg', 66, 36),
  ('amita-b', 'Amita Boost Πορτοκάλι Νεκταρίνι', '330ml', 2.2, 'juice', '/images/products/amita-boost.jpg', 67, 36),
  ('rb', 'Red Bull', '250ml', 2.2, 'energy', '/images/products/redbull.jpg', 68, 36),
  ('rbsf', 'Red Bull Sugarfree', '250ml, χωρίς ζάχαρη', 2.2, 'energy', '/images/products/redbull.jpg', 69, 36),
  ('hell', 'Hell Classic', '250ml', 1.5, 'energy', '/images/products/hell-classic.jpg', 70, 36),
  ('hellz', 'Hell Zero', '250ml, χωρίς ζάχαρη', 1.5, 'energy', '/images/products/hell-zero.jpg', 71, 36),
  ('ft', 'Full Throttle', '500ml', 2.2, 'energy', '/images/products/full-throttle.jpg', 72, 36),
  ('mon-ml', 'Monster Mango Loco', '500ml', 2.5, 'energy', '/images/products/monster-mango-loco.jpg', 73, 36),
  ('mon-doc', 'Monster The Doctor', '500ml', 2.5, 'energy', '/images/products/monster-doctor.jpg', 74, 36),
  ('mon-docz', 'Monster The Doctor Zero', '500ml', 2.5, 'energy', '/images/products/monster-doctor-zero.jpg', 75, 36),
  ('mon-ur', 'Monster Ultra Red', '500ml', 2.5, 'energy', '/images/products/monster-ultra-red.jpg', 76, 36),
  ('mon-uw', 'Monster Ultra White', '500ml', 2.5, 'energy', '/images/products/monster-ultra-white.jpg', 77, 36),
  ('mon-ug', 'Monster Ultra Gold', '500ml', 2.5, 'energy', '/images/products/monster-ultra-gold.jpg', 78, 36),
  ('mon-uf', 'Monster Ultra Fiesta Mango', '500ml', 2.5, 'energy', '/images/products/monster-ultra-fiesta.jpg', 79, 36),
  ('mon-pp', 'Monster Pipeline Punch', '500ml', 2.5, 'energy', '/images/products/monster-pipeline.jpg', 80, 36),
  ('mon-pac', 'Monster Pacific Punch', '500ml', 2.5, 'energy', '/images/products/monster-pacific.jpg', 81, 36),
  ('mon-mon', 'Monster Monarch', '500ml', 2.5, 'energy', '/images/products/monster-monarch.jpg', 82, 36),
  ('mon-lan', 'Monster Lando Norris', '500ml', 2.5, 'energy', '/images/products/monster-lando.jpg', 83, 36),
  ('mon-rr', 'Monster Ruby Red', '500ml', 2.5, 'energy', '/images/products/monster-ruby-red.jpg', 84, 36),
  ('mon-rio', 'Monster Rio Punch', '500ml', 2.5, 'energy', '/images/products/monster-rio.jpg', 85, 36),
  ('mon-str', 'Monster Strawberry Dreams', '500ml', 2.5, 'energy', '/images/products/monster-strawberry.jpg', 86, 36),
  ('mon-vik', 'Monster Viking Berry', '500ml', 2.5, 'energy', '/images/products/monster-viking.jpg', 87, 36),
  ('mon-ba', 'Monster Bad Apple', '500ml', 2.5, 'energy', '/images/products/monster-bad-apple.jpg', 88, 36),
  ('mon-z', 'Monster Zero Sugar', '500ml', 2.5, 'energy', '/images/products/monster-zero.jpg', 89, 36),
  ('bang-ch', 'Bang Black Cherry Vanilla', '500ml', 2.8, 'energy', '/images/products/bang-cherry.jpg', 90, 36),
  ('bang-br', 'Bang Blue Razz', '500ml', 2.8, 'energy', '/images/products/bang-blue-razz.jpg', 91, 36),
  ('bang-cc', 'Bang Cotton Candy', '500ml', 2.8, 'energy', '/images/products/bang-cotton.jpg', 92, 36),
  ('bang-pm', 'Bang Peach Mango', '500ml', 2.8, 'energy', '/images/products/bang-peach-mango.jpg', 93, 36),
  ('wat', 'Νερό', '500ml, κρύο', 0.5, 'market', '/images/products/water.jpg', 94, 36),
  ('ivi', 'Ivi Νερό 1.5L', 'Εξάδα', 1.0, 'market', '/images/products/ivi-water.jpg', 95, 36),
  ('choco', 'Σοκολάτα', 'Μπάρα', 1.8, 'market', '/images/products/chocolate.jpg', 96, 36),
  ('chips', 'Πατατάκια', 'Κλασική σακούλα', 1.5, 'market', '/images/products/chips.jpg', 97, 36),
  ('gum', 'Τσίχλες', 'Για μετά τον καφέ', 0.8, 'market', '/images/products/gum.jpg', 98, 36),
  ('marl', 'Marlboro Red', 'Κόκκινο πακέτο', 5.5, 'smokes', '/images/products/marlboro.jpg', 99, 24),
  ('marlg', 'Marlboro Gold', 'Χρυσό πακέτο', 5.5, 'smokes', '/images/products/pack-gold.jpg', 100, 24),
  ('marlt', 'Marlboro Touch', 'Slim', 5.5, 'smokes', '/images/products/pack-slim.jpg', 101, 24),
  ('winst', 'Winston Classic', 'Κλασικό', 5.2, 'smokes', '/images/products/winston.jpg', 102, 24),
  ('winstb', 'Winston Blue', 'Μπλε', 5.2, 'smokes', '/images/products/pack-blue.jpg', 103, 24),
  ('davi', 'Davidoff Slim', 'Slim', 5.8, 'smokes', '/images/products/davidoff.jpg', 104, 24),
  ('davic', 'Davidoff Classic', 'Κλασικό', 5.8, 'smokes', '/images/products/davidoff.jpg', 105, 24),
  ('camely', 'Camel Yellow', 'Κίτρινο', 5.2, 'smokes', '/images/products/pack-gold.jpg', 106, 24),
  ('camelb', 'Camel Blue', 'Μπλε', 5.2, 'smokes', '/images/products/pack-blue.jpg', 107, 24),
  ('lucky', 'Lucky Strike', 'Κόκκινο', 5.0, 'smokes', '/images/products/pack-red.jpg', 108, 24),
  ('parl', 'Parliament', 'Aqua slim', 5.8, 'smokes', '/images/products/pack-slim.jpg', 109, 24),
  ('kar', 'Karelia Red', 'Κόκκινο', 4.8, 'smokes', '/images/products/pack-red.jpg', 110, 24),
  ('kars', 'Karelia Slim', 'Slim', 5.0, 'smokes', '/images/products/pack-slim.jpg', 111, 24),
  ('pall', 'Pall Mall', 'Κόκκινο', 4.7, 'smokes', '/images/products/pack-gold.jpg', 112, 24),
  ('lm', 'L&M Blue', 'Μπλε', 4.8, 'smokes', '/images/products/pack-blue.jpg', 113, 24),
  ('assos', 'Assos', 'Διεθνές', 4.5, 'smokes', '/images/products/pack-red.jpg', 114, 24),
  ('chest', 'Chesterfield', 'Κόκκινο', 4.7, 'smokes', '/images/products/pack-red.jpg', 115, 24),
  ('ter-br', 'Terea Bronze', 'IQOS ILUMA · ζεστό χαρμάνι', 4.0, 'heat', '/images/products/terea-warm.jpg', 116, 24),
  ('ter-si', 'Terea Sienna', 'IQOS ILUMA · νότες ξύλου', 4.0, 'heat', '/images/products/terea-warm.jpg', 117, 24),
  ('ter-am', 'Terea Amber', 'IQOS ILUMA · ισορροπημένο', 4.0, 'heat', '/images/products/terea-warm.jpg', 118, 24),
  ('ter-ru', 'Terea Russet', 'IQOS ILUMA · έντονο', 4.0, 'heat', '/images/products/terea-warm.jpg', 119, 24),
  ('ter-tk', 'Terea Teak', 'IQOS ILUMA · πλούσιο', 4.0, 'heat', '/images/products/terea-warm.jpg', 120, 24),
  ('ter-tu', 'Terea Turquoise', 'IQOS ILUMA · ζωηρό', 4.0, 'heat', '/images/products/terea-cool.jpg', 121, 24),
  ('ter-ye', 'Terea Yellow', 'IQOS ILUMA · αρωματικό', 4.0, 'heat', '/images/products/terea-cool.jpg', 122, 24),
  ('ter-sv', 'Terea Silver', 'IQOS ILUMA · απαλό', 4.0, 'heat', '/images/products/terea-cool.jpg', 123, 24),
  ('evo-bu', 'Ploom EVO Burgundy', 'Ράβδοι καπνού Ploom', 4.25, 'heat', '/images/products/evo-pack.jpg', 124, 24),
  ('evo-tn', 'Ploom EVO Tan', 'Πλούσιο, γλυκό', 4.25, 'heat', '/images/products/evo-pack.jpg', 125, 24),
  ('evo-ga', 'Ploom EVO Garnet', 'Αρωματικό', 4.25, 'heat', '/images/products/evo-pack.jpg', 126, 24),
  ('evo-go', 'Ploom EVO Gold', 'Ήπιο χαρμάνι', 4.25, 'heat', '/images/products/pack-gold.jpg', 127, 24),
  ('evo-sv', 'Ploom EVO Silver', 'Απαλή γεύση καπνού', 4.25, 'heat', '/images/products/pack-slim.jpg', 128, 24),
  ('evo-gr', 'Ploom EVO Green', 'Φρεσκάδα', 4.25, 'heat', '/images/products/neo-mint.jpg', 129, 24),
  ('evo-te', 'Ploom EVO Teal', 'Δροσερές νότες', 4.25, 'heat', '/images/products/terea-cool.jpg', 130, 24),
  ('neo-cl', 'glo neo Classic Tobacco', '20 ράβδοι · glo Hyper', 3.0, 'heat', '/images/products/neo-pack.jpg', 131, 24),
  ('neo-go', 'glo neo Golden Tobacco', 'Κλασικό χρυσό', 3.0, 'heat', '/images/products/neo-pack.jpg', 132, 24),
  ('neo-te', 'glo neo Terracotta', 'Πλούσιος καπνός', 3.0, 'heat', '/images/products/neo-pack.jpg', 133, 24),
  ('neo-az', 'glo neo Azure', 'Δροσερές νότες', 3.0, 'heat', '/images/products/terea-cool.jpg', 134, 24),
  ('neo-sc', 'glo neo Scarlet', 'Ισορροπημένο', 3.0, 'heat', '/images/products/evo-pack.jpg', 135, 24),
  ('neo-gr', 'glo neo Green', 'Μέντα', 3.0, 'heat', '/images/products/neo-mint.jpg', 136, 24),
  ('neo-ar', 'glo neo Arctic', 'Έντονη δροσιά', 3.0, 'heat', '/images/products/neo-mint.jpg', 137, 24),
  ('v1-tob', 'VEEV ONE Classic Tobacco', 'Pod · καπνός', 3.2, 'heat', '/images/products/veev-tobacco.jpg', 138, 24),
  ('v1-bal', 'VEEV ONE Balanced Tobacco', 'Pod · καφές & καπνός', 3.2, 'heat', '/images/products/veev-tobacco.jpg', 139, 24),
  ('v1-mint', 'VEEV ONE Blue Mint', 'Pod · μέντα', 3.2, 'heat', '/images/products/veev-mint.jpg', 140, 24),
  ('v1-sea', 'VEEV ONE Sea Mint', 'Pod · θαλασσινή μέντα', 3.2, 'heat', '/images/products/veev-mint.jpg', 141, 24),
  ('v1-str', 'VEEV ONE Strawberry', 'Pod · φράουλα', 3.2, 'heat', '/images/products/veev-fruit.jpg', 142, 24),
  ('v1-man', 'VEEV ONE Mango', 'Pod · μάνγκο', 3.2, 'heat', '/images/products/veev-fruit.jpg', 143, 24),
  ('v1-blu', 'VEEV ONE Blueberry', 'Pod · blueberry', 3.2, 'heat', '/images/products/veev-fruit.jpg', 144, 24),
  ('v1-wat', 'VEEV ONE Watermelon', 'Pod · καρπούζι', 3.2, 'heat', '/images/products/veev-fruit.jpg', 145, 24),
  ('v1-gra', 'VEEV ONE Grape', 'Pod · σταφύλι', 3.2, 'heat', '/images/products/veev-fruit.jpg', 146, 24),
  ('v1-app', 'VEEV ONE Sour Apple', 'Pod · πράσινο μήλο', 3.2, 'heat', '/images/products/veev-fruit.jpg', 147, 24),
  ('v1-che', 'VEEV ONE Cherry', 'Pod · κεράσι', 3.2, 'heat', '/images/products/veev-fruit.jpg', 148, 24),
  ('v1-mel', 'VEEV ONE Melon Coconut', 'Pod · πεπόνι καρύδα', 3.2, 'heat', '/images/products/veev-fruit.jpg', 149, 24),
  ('vp-gold', 'VEEV Prime Gold Tobacco', 'Pod inPRIME · καπνός', 4.0, 'heat', '/images/products/veev-tobacco.jpg', 150, 24),
  ('vp-mint', 'VEEV Prime Blue Mint', 'Pod inPRIME · μέντα', 4.0, 'heat', '/images/products/veev-mint.jpg', 151, 24),
  ('vp-str', 'VEEV Prime Strawberry', 'Pod inPRIME · φράουλα', 4.0, 'heat', '/images/products/veev-fruit.jpg', 152, 24),
  ('vp-app', 'VEEV Prime Sour Apple', 'Pod inPRIME · μήλο', 4.0, 'heat', '/images/products/veev-fruit.jpg', 153, 24),
  ('vp-ll', 'VEEV Prime Lemon Lime', 'Pod inPRIME · εσπεριδοειδή', 4.0, 'heat', '/images/products/veev-mint.jpg', 154, 24),
  ('vp-brs', 'VEEV Prime Blue Raspberry', 'Pod inPRIME · raspberry', 4.0, 'heat', '/images/products/veev-fruit.jpg', 155, 24),
  ('vp-che', 'VEEV Prime Cherry', 'Pod inPRIME · κεράσι', 4.0, 'heat', '/images/products/veev-fruit.jpg', 156, 24)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  cat = excluded.cat,
  photo = excluded.photo,
  sort_order = excluded.sort_order;
